### ISSUE TITLE
Unable to install speaker.js on ubuntu

### ISSUE THREAD

**Issue by chetandhembre** [TooTallNate/node-speaker#1]
getting this error!! do check it ..

make: Entering directory `/media/Java/speaker/Delivery.js-master/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
make: Leaving directory`/media/Java/speaker/Delivery.js-master/node_modules/speaker/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/chetand/nvm/v0.8.11/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Linux 2.6.38-8-generic
gyp ERR! command "node" "/home/chetand/nvm/v0.8.11/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/Java/speaker/Delivery.js-master/node_modules/speaker
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.6.11
gyp ERR! not ok 
npm ERR! speaker@0.0.5 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the speaker@0.0.5 install script.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.38-8-generic
npm ERR! command "/home/chetand/nvm/v0.8.11/bin/node" "/home/chetand/nvm/v0.8.11/bin/npm" "install" "speaker"
npm ERR! cwd /media/Java/speaker/Delivery.js-master
npm ERR! node -v v0.8.11
npm ERR! npm -v 1.1.62
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/Java/speaker/Delivery.js-master/npm-debug.log
npm ERR! not ok code 0

**Comment by Richardssen** [comment]
TooTallNate  thanks so muchs
