### ISSUE TITLE
RFC: Consider changing the playback backend to libao

### ISSUE THREAD

**Issue by ezequielgarcia** [TooTallNate/node-speaker#101]
### Why?
Ripping off mpg123's playback logic is smart, but it requires maintaining mpg123 as a third-party dependency.

### OK, really, *why*?
To be completely honest, mpg123 failed to output properly with some simple tests. I was wondering how much of a rabbit hole the debugging would be when I remembered that a problem often has many solutions.

### Why libao?
Libao is a cross-platform audio library that allows programs to output audio using a simple API on a wide variety of platforms. It currently supports:
- Null output (handy for testing without a sound device)
- WAV files
- AU files
- RAW files
- OSS (Open Sound System, used on Linux and FreeBSD)
- ALSA (Advanced Linux Sound Architecture)
- aRts (Analog RealTime Synth, used by KDE)
- PulseAudio (next generation GNOME sound server)
- esd (EsounD or Enlightened Sound Daemon)
- Mac OS X
- Windows (98 and later)
- AIX
- Sun/NetBSD/OpenBSD
- IRIX
- NAS (Network Audio Server)
- RoarAudio (Modern, multi-OS, networked Sound System)
- OpenBSD's sndio

The API is _really_ simple.

### My proposal
See https://www.npmjs.com/package/libao.

### Thanks
Thanks to @TooTallNate for writing node-speaker, from which I took most of the binding code.

**Comment by TooTallNate** [comment]
This is great!

**Comment by LinusU** [comment]
Awesome!

**Comment by ezequielgarcia** [comment]
@TooTallNate so... you guys open to this idea? should I prepare and submit a PR to see how it goes?

I just have Linux systems, so not sure how can we get some mac and windows testing. Also, I'm wondering how much breakage we will get by changing the backend. Maybe we can make it optional (mpg123 or libao, via some build time parameter) for now?

**Comment by MexXxo** [comment]
I suggest to make a new major version. Than the switch will be done via semver :)

**Comment by LinusU** [comment]
I think we should make it a major version, I can test on macOS

**Comment by dsteinman** [comment]
Whatever happened with this?  Is this working?  Does it work in Mac, Windows, and Linux??

If your code is working, and is not and will not be merged into the main branch, I'd suggest publishing a new npm package named `speaker-libao`

**Comment by ezequielgarcia** [comment]
@dsteinman Sorry, I am no longer working or interested in nodejs. Feel free to pick up this and do whatever you want with it! :)

**Comment by dsteinman** [comment]
> @dsteinman Sorry, I am no longer working or interested in nodejs. Feel free to pick up this and do whatever you want with it! :)

Okay, I may do that.  There's a whole bunch of problems with the speaker package and this patch may help.  Thanks for writing it!
