### ISSUE TITLE
Best way to play multiple input streams

### ISSUE THREAD

**Issue by mhammerc** [TooTallNate/node-speaker#115]
Hello!

I want to play multiple PCM streams. Let's say I can maximum play 5 streams at the same time. What's the best ?
- Creating five Speaker instance and keeping them in memory, piping them as needed.
- Creating only one Speaker instance, but mixing multiple streams into one with a package like **https://www.npmjs.com/package/audio-mixer**.

Thanks!

**Comment by LinusU** [comment]
Did you find an answer to this? :)

My gut feeling is that it’s better to let the system do the mixing instead of Node, but I might be wrong.

Also, mixing in Node.js would avoid crossing the JS/C++ boundary once for each chunk of each stream, so that could be beneficial...

**Comment by mhammerc** [comment]
Hello Linus !
I tried mixing from node, but I got segfaults on pipe close, as far as I remember.
So I tried node-mpg123 but we were suffering a bit of latency.

Instead, we developped our own Rust solution based on [rodio](https://github.com/tomaka/rodio): [node-rodio](https://github.com/YellowInnovation/node-rodio) !
