### ISSUE TITLE
Crashes after playing audio on Electron

### ISSUE THREAD

**Issue by jottocraft** [TooTallNate/node-speaker#116]
I'm trying to run this in Electron, and got everything mostly working by running `npm rebuild speaker --target=2.0.5 --arch=x64 --target_arch=x64 --dist-url=https://atom.io/download/electron --runtime=electron` after installing the package. The only problem is, after the speaker finishes playing the audio, the page disappears and the devtools disconnect from the page.

EDIT: I've fixed this issue for now by not calling speaker.end() which seems to be causing the issue

**Comment by derhuerst** [comment]
Please post how you have solved the issues, so that others don't have to ask the question again.

**Comment by LinusU** [comment]
@jottocraft added this edit when the issue was closed:

> EDIT: I've fixed this issue for now by not calling speaker.end() which seems to be causing the issue

👍
