### ISSUE TITLE
Inconsistencies between declared TypeScript export and actual export

### ISSUE THREAD

**Issue by fwcd** [TooTallNate/node-speaker#127]
The TypeScript declaration file declares `Speaker` as a `default` export:

https://github.com/TooTallNate/node-speaker/blob/f365fc8b84c0a856c1bdc71255da01d7aee6ac02/index.d.ts#L20-L27

If that was the case, `Speaker` could be imported with the following syntax:

```typescript
import Speaker from "speaker";
```

This does not work, however, since the actual file does not assign `exports.default`, but rather `exports`:

https://github.com/TooTallNate/node-speaker/blob/f365fc8b84c0a856c1bdc71255da01d7aee6ac02/index.js#L353-L357

The correct way to import `Speaker` would be to use

```typescript
import * as Speaker from "speaker";
```

...which yields the following (incorrect) error by the compiler though:

```
src/output/SpeakerOutput.ts:6:19 - error TS2709: Cannot use namespace
'Speaker' as a type.

6  private speaker: Speaker;
                    ~~~~~~~
9       this.speaker = new Speaker(options);
                       ~~~~~~~~~~~~~~~~~~~~
```

**Comment by LinusU** [comment]
I think that #128 should be the correct way to declare this, could you try and see that it works for you?

btw, the correct way to import this module should be `import Speaker = require('speaker')` unless you are using synthetic es module imports...

**Comment by fwcd** [comment]
```typescript
import Speaker from "speaker";
```

seems to work fine, thanks!
