### ISSUE TITLE
crash on windows 10, node 10

### ISSUE THREAD

**Issue by checksummaster** [TooTallNate/node-speaker#131]
At the event  "close", my application exit.
to fix that, i remove "delete ao->device;" (see below) but I'm not sure why .., maybe will leak but working.

NAN_METHOD(Close) {
  Nan::EscapableHandleScope scope;
  audio_output_t *ao = UnwrapPointer<audio_output_t *>(info[0]);
  ao->close(ao);
  int r = 0;
  if (ao->deinit) {
    r = ao->deinit(ao);
  }
  //delete ao->device;
  info.GetReturnValue().Set(scope.Escape(Nan::New<v8::Integer>(r)));
}

**Comment by JonSilver** [comment]
I'm still experiencing this behaviour even with the new v0.5.0. The app plays one stream, piped from lame, then exits with no error. Breakpointing on all or uncaught exceptions doesn't break. If the pipe from lame goes nowhere, the app remains running.

Node 10.17.0
Windows 10

**Comment by LinusU** [comment]
I'm sorry to hear that, unfortunately I don't have access to a Windows 10 computer to try on 🤔 

Would you be able to try commenting this line out:

https://github.com/TooTallNate/node-speaker/blob/8dc9e9cbc042e88a108c3381adac958f23cb4369/src/binding.c#L157

If that makes it work, we are probably double freeing that one. Just removing the free is probably the right thing to do, but it might be good to look at the source code for mpg123 to make sure that it's actually freeing it for us...

**Comment by JonSilver** [comment]
OK so I commented out the line, ran an `npm rebuild speaker`, and the test app worked. Is there a test that can ascertain whether it should be freed?

**Comment by LinusU** [comment]
Hmm, potentially this is not a double free, but rather that we are trying to free a static string 😁 

https://github.com/TooTallNate/node-speaker/blob/20627e12f2628da8313544f5a92813f78cb3e68e/deps/mpg123/src/output/win32.c#L61

I need to dig deeper into this, potentially every backend works differently 😭 

Hopefully I'll get some time this weekend! Thank you for testing 👏

**Comment by LinusU** [comment]
Hmm, since the `open` call in the win32 output always overwrites the current device, I guess that it's leaking that memory already 🤷‍♂ 

Maybe the best thing for us to do is store the pointer to the device string out of band, and then free it after we've closed the ao instance 🤔

**Comment by JonSilver** [comment]
Sounds like a good plan. :)

**Comment by LinusU** [comment]
@JonSilver could you try out #139 and see if that solves the problem for you? ☺️

**Comment by JonSilver** [comment]
@LinusU Patch applied and rebuilt... That seems to fix things nicely :)

**Comment by LinusU** [comment]
Awesome, I'll push a new release!

**Comment by LinusU** [comment]
Released in [🚢 0.5.1 / 2019-12-16](https://github.com/TooTallNate/node-speaker/releases/tag/v0.5.1)

**Comment by JonSilver** [comment]
Cool... I'll await the [npmjs.com](https://www.npmjs.com/package/speaker) release :)

**Comment by LinusU** [comment]
It's already live 😉 

<img width="363" alt="Screenshot 2019-12-16 at 16 27 59" src="https://user-images.githubusercontent.com/189580/70924187-077f1500-2021-11ea-95f9-c2ad690fd241.png">
