### ISSUE TITLE
PulseAudio binding fails on Raspbian jessie

### ISSUE THREAD

**Issue by WeeJeWel** [TooTallNate/node-speaker#42]
After installing node-speaker `npm install speaker --mpg123-backend=pulse` on a Raspberry Pi with Raspbian jessie, the following error is given after `require('speaker')`:

`node: symbol lookup error: /root/pa/node_modules/speaker/build/Release/binding.node: undefined symbol: pa_simple_new`

All pulseaudio packages have been installed, and pa_simple_new can be found in libpulse.

**Comment by ReneHollander** [comment]
Same problem. Could it be a linking issue?

**Comment by TooTallNate** [comment]
Ya most likely...

**Comment by TooTallNate** [comment]
We probably need to add something to the mpg123.gyp file, to specifiy the lib to link to. Similar to https://github.com/TooTallNate/node-speaker/blob/08d9b63462632c34c93f0982a4c9d4402e71ce02/deps/mpg123/mpg123.gyp#L188-L194, but for "pulse" backend.

**Comment by ReneHollander** [comment]
I will try it. Thanks for the tip!
