### ISSUE TITLE
Installation fails on Raspbian

### ISSUE THREAD

**Issue by 8power8** [TooTallNate/node-speaker#44]
While installing on Raspbian I get 
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.33"`
`gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/nodefiles/node_modules/speaker/.node-gyp"`
`make: Entering directory '/home/pi/nodefiles/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
compilation terminated.`
`deps/mpg123/output.target.mk:97: recipe for target` `'Release/obj.target/output/deps/mpg123/src/output/alsa.o' failed`
`make: *** [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1`
`make: Leaving directory '/home/pi/nodefiles/node_modules/speaker/build'`
`gyp ERR! build error` 
`gyp ERR! stack Error: `make` failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)`
`gyp ERR! stack     at ChildProcess.emit (events.js:98:17)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)`
`gyp ERR! System Linux 3.12.30+`
`gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`
`gyp ERR! cwd /home/pi/nodefiles/node_modules/speaker`
`gyp ERR! node -v v0.10.33`
`gyp ERR! node-gyp -v v1.0.1`
`gyp ERR! not ok `

Though this seems not be directly related to speaker module, it prevents from installing it.
I tried with sudo npm install --unsafe-perm -g speaker without success.

**Comment by footniko** [comment]
sudo apt-get install libasound2-dev

**Comment by 8power8** [comment]
Thanks ! I figured out the same, but forgot to close the issue.
