### ISSUE TITLE
Set volume from 0 -> 100%

### ISSUE THREAD

**Issue by G33kLabs** [TooTallNate/node-speaker#54]
First thanks for this package, it's awesome !

During one of my project, I play music and use tts features for orders validation as 'playing next song', 'stop music'...
It would be better if I could set tts volume to 40% for example and then if the music volume is high, it will not surprise me sometimes.

So, a 'volume' parameter on Speaker instantiation would be great.

**Comment by jkeylu** [comment]
see this package: [https://github.com/jkeylu/node-mpg123-util](https://github.com/jkeylu/node-mpg123-util)

usage: [https://github.com/jkeylu/vinyl-singer](https://github.com/jkeylu/vinyl-singer)

**Comment by G33kLabs** [comment]
Perfect, you've made exactly what I need !
