### ISSUE TITLE
Stalls on Windows 10 when instantiating

### ISSUE THREAD

**Issue by madforce** [TooTallNate/node-speaker#66]
Found another issue with instantiating on Windows similar to previously solved by @RTK. Same solution for Windows 10 except for a later version from the mpeg123 library.

Copy win32.c and win32_wasapi.c files in the output directory with the latest and then node-gyp rebuild.

I tried copying the whole library verbatim but it then failed to build, so the above hacky solution will have to do.

I have forked the project with the files popped in there let me know if you want a pull request

Cheers
Marty

**Comment by stepankuzmin** [comment]
Confirming this issue.

**Comment by MathijsvVelde** [comment]
It is this Commit: 1f22378
