### ISSUE TITLE
Play 2 files at the same time

### ISSUE THREAD

**Issue by elachere** [TooTallNate/node-speaker#67]
Hi,

I'm trying to play 2 files at the same time, with 2 Speaker instances, like this : 

var speaker1;
      speaker2;
      decoder = new lame.Decoder();
      stream1 = fs.createReadStream('path/to/file1.mp3');
      stream2 = fs.createReadStream('path/to/file2.mp3');

stream1.pipe(decoder).on('format', function(format){
        speaker1 = new Speaker(format);
        this.pipe(speaker1);
});

stream2.pipe(decoder).on('format', function(format){
        speaker2 = new Speaker(format);
        this.pipe(speaker2);
});

I can't get a proper sound, it's just screaming and I lose data, here's some logs I got : 

Note: Illegal Audio-MPEG-Header 0x4582c664 at offset 131400.
Note: Trying to resync...
Note: Skipped 220 bytes in input.

Is there any way to do this ?

Thanks in advance

**Comment by tianweiliu** [comment]
You need to create a new decoder instance for each stream.

**Comment by LinusU** [comment]
You probably have to pipe both streams to a stream that can mix them together, then pipe that stream to the speaker...
