### ISSUE TITLE
failed install on the macosx 

### ISSUE THREAD

**Issue by chinaguo** [TooTallNate/node-speaker#83]
child_process: customFds option is deprecated, use stdio instead.
  CC(target) Release/obj.target/output/deps/mpg123/src/output/coreaudio.o
  LIBTOOL-STATIC Release/liboutput.a
libtool: unrecognized option `-static'
libtool: Try`libtool --help' for more information.
make: **\* [Release/liboutput.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/guoxinchun1/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "node" "/Users/guoxinchun1/.nvm/versions/node/v0.12.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/guoxinchun1/project/nodejs/electron/electron-quick-speeker/node_modules/speaker
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/guoxinchun1/.nvm/versions/node/v0.12.0/bin/node" "/Users/guoxinchun1/.nvm/versions/node/v0.12.0/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guoxinchun1/project/nodejs/electron/electron-quick-speeker/npm-debug.log

**Comment by timothymugayi** [comment]
There seems to be a problem with node v12.x.x at least on a mac. The solution that seems to work for me is performing a downgrade from node@12.x.x to 1.10.0. Best to use [nvm](https://github.com/nvm-sh/nvm) so you can switch between node versions easily. 

```
$ nvm install 11.10.0`
$ npm install speaker --mpg123-backend=openal  --save
```

**Comment by KamilSzczepankiewicz** [comment]
Was anyone able to resolve this issue/error?

**Comment by saikatmitra91** [comment]
Am also facing the issue. And the issue is marked closed :)

**Comment by ATSiem** [comment]
I can't get `speaker` to install on the latest MacOS with all relevant updates.

There's an issue when node-gyp tries to rebuild the speaker package, specifically a configuration issue in binding.gyp or mpg123.gyp. The 'mpg123_cpu is not defined'.)

 I tried myriad Node 14-latest/Python 3.8-latest versions...

**Comment by kamalkech** [comment]
This is very old issue and still not fixed !!!
Get same error here !

**Comment by nilsroemer** [comment]
Same

**Comment by Sengulair** [comment]
Same

**Comment by phin** [comment]
Same error, repro steps and workarounds tried above, Jan 28th 2024 :)

**Comment by msshang18** [comment]
same error

**Comment by GatoVuelta** [comment]
Same issue here. Node v20 (Tried also with v18, v16, v11 with no luck)
