### ISSUE TITLE
use node-pre-gyp to improve experience

### ISSUE THREAD

**Issue by MylesBorins** [TooTallNate/node-speaker#89]
would you have any interest in adding node-pre-gyp? It allows you to build binaries for various deployment targets and pre publish them online, allowing individuals to not have to compile locally.

I'd be up for putting together a PR if you are open to review / merging a feature like this.

**Comment by TooTallNate** [comment]
I wouldn't be necessarily against it. `node-pre-gyp` uses S3 right… who pays for the bandwidth?

**Comment by TheAlphaNerd** [comment]
it seems to be sponsored by mapbox.

**Comment by TooTallNate** [comment]
I see. Patches welcome!
